package io.samuelagesilas.nbafinals.models

data class ChampionsModel(val id: Int,
                          val year: Int,
                          val team: String,
                          val game: Int,
                          val win: Boolean,
                          val home: Boolean,
                          val mp: Int,
                          val fg: Int,
                          val fga: Int,
                          val fgp: Double,
                          val tp: Int,
                          val tpa: Int,
                          val tpp: Double,
                          val ft: Int,
                          val fta: Int,
                          val ftp: Double,
                          val orb: Int,
                          val drb: Int,
                          val trb: Int,
                          val ast: Int,
                          val stl: Int,
                          val blk: Int,
                          val tov: Int,
                          val pf: Int,
                          val pts: Int)